[project]
name = "ctd-tna-to-ehri-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pip-system-certs>=5.3",
    "requests>=2.32.5",
    "treelib>=1.8.0",
    "xlutils>=2.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
